include("abstract.jl")
include("capacitymultiplier.jl")
include("duration.jl")
include("variablecapacity.jl")
include("fixedcapacity.jl")
include("variablecomposedcapacity.jl")
include("fixedcomposedcapacity.jl")
