include("variablecapacity.jl")
include("variablecomposedcapacity.jl")
include("fixedcomposedcapacity.jl")
include("fixedcapacity.jl")
include("capacitymultiplier.jl")
include("fleetcommitment.jl")
include("ramping.jl")
include("yearlysum.jl")
include("duration.jl")
include("reserve.jl")

include("costs/_includes.jl")
